// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uflnppjyvjexnvpnfcxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmbG5wcGp5dmpleG52cG5mY3htIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3ODkwMjAsImV4cCI6MjA2NDM2NTAyMH0.5-YCE2gcxaBMvnCbuZLLveTi_EVeXEFyX7R0fRBYudg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);